defaults: &defaults
  working_directory: ~/rxbackoff
  docker:
    - image: circleci/android:api-27-alpha
  environment:
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "rxjava2/build.gradle" }}-{{ checksum  "ktx/build.gradle" }}-{{ checksum  "example/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths: ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "rxjava2/build.gradle" }}-{{ checksum  "ktx/build.gradle" }}-{{ checksum  "example/build.gradle" }}
      - run:
          name: Run Core Assemble
          command: ./gradlew :core:assembleRelease
      - run:
          name: Run RxJava2 Assemble
          command: ./gradlew :rxjava2:assembleRelease
      - run:
          name: Run KTX Assemble
          command: ./gradlew :ktx:assembleRelease
      - run:
          name: Run Core Test Coverage
          command: ./gradlew :core:testDebugUnitTestCoverage
      - run:
          name: Run RxJava2 Test Coverage
          command: ./gradlew :rxjava2:testDebugUnitTestCoverage
      - run:
          name: Run KTX Test Coverage
          command: ./gradlew :ktx:testDebugUnitTestCoverage
      - run:
          name: Run Example test
          command: ./gradlew :example:test
      - store_artifacts:
          path: ./core/build/outputs/
          destination: outputs/core/
      - store_artifacts:
          path: ./core/build/reports/
          destination: reports/core/
      - store_artifacts:
          path: ./rxjava2/build/outputs/
          destination: outputs/rxjava2/
      - store_artifacts:
          path: ./rxjava2/build/reports/
          destination: reports/rxjava2/
      - store_artifacts:
          path: ./ktx/build/outputs/
          destination: outputs/ktx/
      - store_artifacts:
          path: ./ktx/build/reports/
          destination: reports/ktx/
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: ./gradlew :core:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  deploy_rxjava2:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: ./gradlew :rxjava2:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  deploy_ktx:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: ./gradlew :ktx:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_core:
          requires:
            - build
          filters:
            tags:
              only: /^core_v.*/
            branches:
              ignore: /.*/
      - deploy_rxjava2:
          requires:
            - build
          filters:
            tags:
              only: /^rxjava2_v.*/
            branches:
              ignore: /.*/
      - deploy_ktx:
          requires:
            - build
          filters:
            tags:
              only: /^ktx_v.*/
            branches:
              ignore: /.*/
