version: 2
jobs:
  build:
    working_directory: ~/rxbackoff
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "example/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths: ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "example/build.gradle" }}
      - run:
          name: Run Assemble
          command: ./gradlew :library:assembleRelease
      - run:
          name: Run Test Coverage
          command: ./gradlew :library:testDebugUnitTestCoverage
      - run:
          name: Run Example test
          command: ./gradlew :example:test
      - store_artifacts:
          path: ./library/build/outputs/
          destination: outputs
      - store_artifacts:
          path: ./library/build/reports/
          destination: reports
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
